/** Canonical list of vehicle body panels used across AI analysis and cost calculation. */
export const PANEL_NAMES = [
  'front_bumper',
  'rear_bumper',
  'bonnet',
  'boot_lid',
  'roof',
  'nearside_front_wing',
  'offside_front_wing',
  'nearside_rear_quarter',
  'offside_rear_quarter',
  'nearside_front_door',
  'offside_front_door',
  'nearside_rear_door',
  'offside_rear_door',
  'nearside_sill',
  'offside_sill',
  'nearside_mirror',
  'offside_mirror',
  'front_windscreen',
  'rear_windscreen',
  'nearside_headlight',
  'offside_headlight',
  'nearside_tail_light',
  'offside_tail_light',
  'grille',
  'tailgate',
] as const;

export type PanelName = (typeof PANEL_NAMES)[number];

/** Human-readable labels for panels. */
export const PANEL_LABELS: Record<PanelName, string> = {
  front_bumper: 'Front Bumper',
  rear_bumper: 'Rear Bumper',
  bonnet: 'Bonnet',
  boot_lid: 'Boot Lid',
  roof: 'Roof',
  nearside_front_wing: 'Nearside Front Wing',
  offside_front_wing: 'Offside Front Wing',
  nearside_rear_quarter: 'Nearside Rear Quarter',
  offside_rear_quarter: 'Offside Rear Quarter',
  nearside_front_door: 'Nearside Front Door',
  offside_front_door: 'Offside Front Door',
  nearside_rear_door: 'Nearside Rear Door',
  offside_rear_door: 'Offside Rear Door',
  nearside_sill: 'Nearside Sill',
  offside_sill: 'Offside Sill',
  nearside_mirror: 'Nearside Mirror',
  offside_mirror: 'Offside Mirror',
  front_windscreen: 'Front Windscreen',
  rear_windscreen: 'Rear Windscreen',
  nearside_headlight: 'Nearside Headlight',
  offside_headlight: 'Offside Headlight',
  nearside_tail_light: 'Nearside Tail Light',
  offside_tail_light: 'Offside Tail Light',
  grille: 'Grille',
  tailgate: 'Tailgate',
};

/** Panel size category for paint cost calculation. */
export const PANEL_SIZE_CATEGORY: Record<PanelName, 'small' | 'medium' | 'large'> = {
  front_bumper: 'large',
  rear_bumper: 'large',
  bonnet: 'large',
  boot_lid: 'large',
  roof: 'large',
  nearside_front_wing: 'medium',
  offside_front_wing: 'medium',
  nearside_rear_quarter: 'large',
  offside_rear_quarter: 'large',
  nearside_front_door: 'large',
  offside_front_door: 'large',
  nearside_rear_door: 'large',
  offside_rear_door: 'large',
  nearside_sill: 'medium',
  offside_sill: 'medium',
  nearside_mirror: 'small',
  offside_mirror: 'small',
  front_windscreen: 'large',
  rear_windscreen: 'large',
  nearside_headlight: 'small',
  offside_headlight: 'small',
  nearside_tail_light: 'small',
  offside_tail_light: 'small',
  grille: 'medium',
  tailgate: 'large',
};
