/** Canonical list of vehicle body panels used across AI analysis and cost calculation. */
export const PANEL_NAMES = [
  'front_bumper',
  'rear_bumper',
  'bonnet',
  'boot_lid',
  'roof',
  'nearside_front_wing',
  'offside_front_wing',
  'nearside_rear_quarter',
  'offside_rear_quarter',
  'nearside_front_door',
  'offside_front_door',
  'nearside_rear_door',
  'offside_rear_door',
  'nearside_sill',
  'offside_sill',
  'nearside_mirror',
  'offside_mirror',
  'front_windscreen',
  'rear_windscreen',
  'nearside_headlight',
  'offside_headlight',
  'nearside_tail_light',
  'offside_tail_light',
  'grille',
  'tailgate',
] as const;

export type PanelName = (typeof PANEL_NAMES)[number];
